### ISSUE TITLE
Make README.md clearer

### ISSUE THREAD

**Issue by Reyncor** [spaceboats/busbus#5]
The readme is a little plain... I see some GTFS processing...

**Comment by ianweller** [comment]
Hi!

I'm going to write some information up to answer your question of "What does this do? What will it do?", and then change the issue title to "Make README.md clearer". :)

busbus is intended to be a system for retrieving transit data in a common way across agencies. It's far from that point yet — so far we've only got GTFS code written, yes. The next step in particular is continuing to process GTFS so that we have knowledge of planned arrivals, and then hook up to the MBTA-realtime API. Then rinse and repeat for every other transit agency we can find.

(We're doing it as part of our senior capstone class for our undergrad in CS — we're still on winter break which should hopefully explain the lack of activity over the last month.)

The Python busbus API is not finalized yet (there's still a couple of changes I have in mind for what's already available), and we'll be working on a web API on top of it as well. And, of course, we need to get some documentation written up.

There's also some documentation about what busbus is supposed to be scattered across the [repos for this organization](https://github.com/spaceboats).

If you're interested in using busbus, I'm very interested in your feedback throughout the development process, through issues or pull requests or pretty much anything.

**Comment by ianweller** [comment]
(I had some test code lying around that pulled specific information from the MBTA provider but I can't seem to find it now. I'll write it up again as part of fixing the README.)

**Comment by Reyncor** [comment]
That was the original title I had in mind. This is an open source Transit Data Aggregator. I stumbled upon this looking for someone trying to fix my problem, which is my city does not even have GTFS or any accessible mass transit information. Schedules are distributed using PDF's and Scheduling is done on a closed source archaic website. I'll keep this project in mind. Thanks!

**Comment by ianweller** [comment]
Could you leave a link to your transit agency's website? We like finding exceptions to the GTFS rule.

**Comment by Reyncor** [comment]
http://centro.org they have something to do with CNYTra. The RochesterTA, and Albany's both support GTFS. I asked them about it... they replied saying it's too difficult... They use Trapeze, which supports GTFS exports. After I offered to help and asked about specifics, they never replied.
